### ISSUE TITLE
How to interpret dejafu's results?

### ISSUE THREAD

**Issue by abailly** [barrucadu/dejafu#129]
I have the following function:

```
waitFor :: (MonadConc m) => Int -> Text -> MVar m [ Message  -> m () ] -> m Bool
waitFor num regex onMsgs = trace ("entering wait for" :: Text) $ do

  sem <- atomically $ newTVar (Pending num)

  timer <- async $ do
    threadDelay $ 60 * 1000 * 1000
    atomically $ writeTVar sem Timeout

  modifyMVar_ onMsgs
    (\msgs -> pure $ (\out ->
                        trace ("waiting " <> msg out) $ when (msg out =~ (toS regex :: ByteString)) $ atomically $ modifyTVar sem decrementPending) : msgs)

  res <- atomically $ do
    s <- readTVar sem
    check (s == Pending 0 || s == Timeout)
    return s

  cancel timer

  trace ("exiting wait for" :: Text) $ return $ res == Pending 0

  where
    decrementPending (Pending 0) = Pending 0
    decrementPending (Pending n) = Pending (n - 1)
    decrementPending x           = x
```

whose purpose is to wait for some message to appear in a stream of logs.

When running `autocheck (C.newEmptyMVar >>= waitFor 1 "Foo")`  I have the following results:

```
entering wait for
[fail] Never Deadlocks (checked: 1)
	[deadlock] S0---------S1----------
[pass] No Exceptions (checked: 1)
[pass] Consistent Result (checked: 1)
False
```

I understand `S0` is the "main" thread and `S1` is the `async` computation. Is this correct? 

Furthermore, I understand that this computation can deadlock, but it is not clear why in this case. IT seems to me there is no way for the `sem` variable to not receive a value, either after some time or if the property becomes true.

**Comment by barrucadu** [comment]
`0` is the main thread and `1` is the `async` computation (you can also give the async computation a name now, thanks to #125, which will show up below the trace as a sort of key).  The `S` means that a thread started *without* pre-empting the previously running thread (a `P` means that there was a pre-emption).

So this trace is fairly easy to read: the main thread ran until it blocked, and then the async thread ran until it blocked or completed, then there were no more runnable threads.  The problem here is actually the call to `modifyMVar_ onMsgs`.  `modifyMVar_` blocks if the MVar is empty, which it is here!  This can be seen from the type of `modifyMVar_`:

```haskell
modifyMVar_ :: MonadConc m => MVar m a -> (a -> m a) -> m ()
```

Because that gives an `a` to the function, it must get an `a` from the MVar first.  So if the MVar is empty, it can only block.

You can get a more wordy trace out which gives you more information about what's going on, and is perhaps easier to read than counting `-`s with the `runSCT` family of functions.  For example:

```
> autocheck (C.newEmptyMVar >>= \v -> C.modifyMVar_ v pure)
[fail] Never Deadlocks (checked: 1)
        [deadlock] S0---
[pass] No Exceptions (checked: 1)
[pass] Consistent Result (checked: 1)
False

> runSCT defaultWay defaultMemType (C.newEmptyMVar >>= \v -> C.modifyMVar_ v pure)
[(Left Deadlock,[(Start main,[(main,WillNewMVar)],NewMVar 1),(Continue,[(main,WillSetMasking False MaskedInterruptible)],SetMasking False MaskedInterruptible),(Continue,[(main,WillTakeMVar 1)],BlockedTakeMVar 1)])]
```

Splitting that into multiple lines and removing the lookahead values, we get this trace:

```
[(Start main,NewMVar 1)
,(Continue,SetMasking False MaskedInterruptible)
,(Continue,BlockedTakeMVar 1)
]
```

**Comment by abailly** [comment]
Of course! Now that you say it, it's pretty obvious :)  This `MVar` is never empty in "real" cases but that's definitely a potential problem. Thanks a lot.
