### ISSUE TITLE
How to handle time in ConcT computations?

### ISSUE THREAD

**Issue by abailly** [barrucadu/dejafu#130]
I have a computation that relies on some timeout (see #129)  for proper execution. I run this function along with another function that starts a thread feeding data and I would like to deterministically assert that the `waitFor` function succeeds if fed data before timeout expires. This requires controlling time in some way in the `threadDelay` invocation. I can see the default implementation of `threadDelay` is `yield` which won't really work because it will yield once but not enough "times".

Is there a way to control this in dejafu? If not, any hints on how this could be done would be much appreciated.

**Comment by abailly** [comment]
So from #131 I infer that a way to handle that problem would be to implement `threadDelay`  as a proper primitive in `concurrent`, is that correct? I would like to be able to control the passing of logical time in order to control and simulate various timeouts. 

I understand that having `threadDelay _ = yield` has this effect because this action becomes a branching point in the states exploration tree, so it does not matter much to actually track the passing of time. Is this also right?

**Comment by barrucadu** [comment]
> So from #131 I infer that a way to handle that problem would be to implement threadDelay as a proper primitive in concurrent, is that correct?

Actually no.  #131 is just about improving the reporting of `threadDelay` in a trace, rather than implementing any notion of time during execution.

Tracking time is difficult, because it *could* be the case that every thread is paused long enough (by the OS swapping out the process or whatever) such that no delay is enough.  It would be technically wrong to say, for instance, that this always prints 3:

```haskell
main = do
    r <- newCRef 3
    fork (threadDelay 1000000 >> writeCRef r 7)
    print =<< readCRef r
```

It's vanishingly unlikely that it would print 7, but it's not impossible!

Now, where #131 could help here is that it would make it possible to implement another mode of testing (beyond the current systematic and random approaches) which does take time into account: driving the system into new schedules which meet some timing constraints.  But that would be a new feature.

**Comment by abailly** [comment]
Alright. I am working on distributed systems, which contain a lot of timeouts everywhere, like when exchanging messages and the like. Having a way to control those timeouts and include them in testing mode would be great because it could probably uncover interesting bugs... What would it take to implement such a mode? At the very least there would be a need to record the passing of time somehow in the state of computations. I would be happy to invest some time and effort on this very topic but I would need some directions.

**Comment by barrucadu** [comment]
Before we go down the new feature rabbit hole... @gdeest @nmattia you guys are doing distributed systems, do you handle timeouts at all?

**Comment by barrucadu** [comment]
I spoke with @gdeest on Monday, and he said that they don't use timeouts, but they have a way of injecting faults which may be useful here.  Hopefully he can give some further information.

**Comment by abailly** [comment]
I know, I have had some discussions with people from Tweag :) My concern may be ill founded though but I feel like I would like some notion of time somewhere in my model, even if only logical.. But maybe it is simpler to extract the timeout to some function and mock it?

**Comment by gdeest** [comment]
Basically, the way we are dealing with errors is by having a global "fail state", mutated by an additional thread. In concurrency tests, we wrap our API with an additional layer that triggers errors accordingly by inspecting this global state. It is a pretty cheap fault injection mechanism, but has served our needs quite well so far.

I haven't given timeouts much thoughts, but IMO, they could be modeled in a similar way. A related idea could be to store an random number generator to detect whether a timeout should be thrown. The most important point being, you should abstract over the actual `timeout` implementation and encode the possibility of failure on top of existing concurrency primitives.

I can provide more details if required.

**Comment by larskuhtz** [comment]
I work on systems where clocks are used as a distributed synchronization mechanism. Delays and timeouts can't be modeled by random failures, since the correctness of the systems depends on the actual values of delays and timeouts. 

I am experimenting with an explicit clock thread, but that introduces a lot of non-determinism, blowing up the search space for systematic exploration. Also, it seems that clocks don't play well with the random search strategies of DejaFu. I wonder, if there are random search strategies that work better with clocks.

There are some tradeoffs for different implementations of a clock. Here is an experimental implementation of a clock (probably still buggy): https://gist.github.com/larskuhtz/9cc714bab35487febff2b9c7df5028b9

**Comment by barrucadu** [comment]
Here's an idea I had, not sure how well it would work out in practice:

1. Change the `Thread` type to also have a countdown, representing how long that thread is delayed:

    ```haskell
    data Thread n r = Thread
      { _continuation :: Action n r
      , _blocking     :: Maybe BlockedOn
      , _delay        :: Maybe Int   -- new
      , _handlers     :: [Handler n r]
      , _masking      :: MaskingState
      }
    ```

2. Then, when choosing a thread to execute, only choose from threads which are unblocked (as is the case now) *and* which are not delayed.
3. After stepping the chosen thread, all delayed threads get their delay reduced, and set to `Nothing` if now `<= 0`.

There's probably a bunch of different strategies for how to reduce the delay.  The simplest would be to just decrement it, but I expect that wouldn't work so well in practice as people tend to use delays of 1000+.

> I am experimenting with an explicit clock thread [...]  Here is an experimental implementation of a clock (probably still buggy): https://gist.github.com/larskuhtz/9cc714bab35487febff2b9c7df5028b9

This is a neat idea, but I agree it's not very friendly to the systematic approach (nor is having a shared mutable "fail state", for that matter).  A better random approach might be to restrict how close or far clock ticks can be from each other.  For example, you could prevent having two ticks of the same clock with no intervening action from a different thread.

---

I am, and will be for the next few months, writing up my Ph.D thesis.  So I may have less time than usual to put into dejafu (although I do still have weekends, and have timetabled Wednesdays as "anything but thesis" days).

I'll keep this issue open, as there's obviously interest in having time *somehow*, and I'm happy to help people if they start hacking on dejafu, but I probably won't be able have a serious go at implementing something myself for a while.

**Comment by robinp** [comment]
@abailly Could you elaborate on why/how the *actual* value of delay important? My intuition is that it's only the fact that there's a delay important. Other events either execute before the delay, or after.

Well, a single delay then is not really important. But then *two* delays can be important relative to each other - but as @barrucadu pointed out, this is probably self-deceptive (unless we are dealing with hard real-time guarantees, which we don't), as execution order could still reverse due to OS things.

So what I take away, are *two* possible approaches:

1) The "I trust my OS won't swap" approach, which is "good enough" but don't bet your atomic reactor on it: have a `delay` in each `Thread` as advised above. Whenever there's a scheduling choice, *either*

     a) choose an unblocked (`delay=0`) thread to run according to exploration policy.
     b) find the *minimal* delay value globally, and subtract that from all nonzero delays. Recurse.

2) The "everything can go wrong" approach, where the delays just don't matter. I guess this is what happens now by default?

**Comment by abailly** [comment]
I am not actively working on this anymore, no need to clutter issues list.
