### ISSUE TITLE
`dontCheck` must be first thing not always enforced, can cause spurious test success

### ISSUE THREAD

**Issue by aherrmann** [barrucadu/dejafu#230]
Thanks for adding `dontCheck` it's very useful. Unfortunately, I found an issue when it is not the very first thing in a test-case.

The haddocks on `dontCheck` state:

> This must be the first thing done in the main thread. Violating this condition will result in the computation failing with IllegalDontCheck.

This does not seem to always be enforced. The following patch adds a few test-cases to `dejafu-tests`  that should all fail because they violate this rule. However, the cases `abortsNever`, `deadlocksNever`, `exceptionsNever`, and `alwaysSame` succeed.

``` diff
diff --git a/dejafu-tests/lib/Integration/SingleThreaded.hs b/dejafu-tests/lib/Integration/SingleThreaded.hs
index 731e313..cfb50ab 100644
--- a/dejafu-tests/lib/Integration/SingleThreaded.hs
+++ b/dejafu-tests/lib/Integration/SingleThreaded.hs
@@ -7,6 +7,7 @@ import           Control.Exception         (ArithException(..),
 import           Test.DejaFu               (Failure(..), gives, gives', isAbort,
                                             isDeadlock, isIllegalDontCheck,
                                             isUncaughtException)
+import qualified Test.DejaFu
 import           Test.DejaFu.Defaults      (defaultLengthBound)

 import           Control.Concurrent.Classy
@@ -267,6 +268,25 @@ hacksTests = toTestList
         v <- newEmptyMVarInt
         dontCheck Nothing $ putMVar v 5

+    , toTestList $ testGroup "Must be very first thing enforced"
+      [ djfuTS n p $ do
+          v <- newEmptyMVarInt
+          dontCheck Nothing $ putMVar v 5
+      | (n, p) <-
+          [ ("abortsNever", Test.DejaFu.abortsNever)
+          , ("abortsAlways", Test.DejaFu.abortsAlways)
+          , ("abortsSometimes", Test.DejaFu.abortsSometimes)
+          , ("deadlocksNever", Test.DejaFu.deadlocksNever)
+          , ("deadlocksAlways", Test.DejaFu.deadlocksAlways)
+          , ("deadlocksSometimes", Test.DejaFu.deadlocksSometimes)
+          , ("exceptionsNever", Test.DejaFu.exceptionsNever)
+          , ("exceptionsAlways", Test.DejaFu.exceptionsAlways)
+          , ("exceptionsSometimes", Test.DejaFu.exceptionsSometimes)
+          , ("alwaysSame", Test.DejaFu.alwaysSame)
+          , ("notAlwaysSame", Test.DejaFu.notAlwaysSame)
+          ]
+      ]
+
     , djfu "Exceeding the length bound aborts the whole computation" (alwaysFailsWith isAbort) $
         dontCheck (Just 1) $ newEmptyMVarInt >> pure ()
```

This can mask other failures. For example, appending two `takeMVar v` instructions to the test-case should make `deadlocksNever` fail. But, due to `dontCheck` not being the very first instruction, the test-case succeeds. It does fail as expected when `dontCheck` is the first thing or missing.

**Comment by barrucadu** [comment]
The issue here is that dejafu has two notions of "failure" which at least three people now have got mixed up.  So I need to fix that.

```
> import qualified Control.Concurrent.Classy as C
> let example1 = do { v <- C.newEmptyMVar; dontCheck Nothing (C.putMVar v 5) }
> resultsSet defaultWay defaultMemType example1
fromList [Left IllegalDontCheck]
```

This program is totally deterministic (so `alwaysSame` passes), doesn't give `Left Abort` (so `abortsNever` passes), doesn't give `Left Deadlock` (so `deadlocksNever` passes), and doesn't give `Left UncaughtException` (so `exceptionsNever` passes).

There's a distinction between a failure in a concurrent computation (deadlocks, uncaught exceptions, misuse of `dontCheck`, etc), and a failing test.  Here, the concurrent computation is failing.

There's no masking of other failures:

```
> let example2 = do { v <- C.newEmptyMVar; dontCheck Nothing (C.putMVar v 5); C.takeMVar v; C.takeMVar v }
> resultsSet defaultWay defaultMemType example2
fromList [Left IllegalDontCheck]
```

The execution stops as soon as it hits the invalid use of `dontCheck`, which is before the deadlock happens.  The result is still just `Left IllegalDontCheck`: that program doesn't deadlock, because it doesn't get that far.

---

So the problem is that half of the time I'm using "failure" to mean "execution failure" and half of the time to mean "test failure".

Do you think it would be clearer if I changed `Failure` to `Incomplete` and then used language like "execution will exit early with `IllegalDontCheck`" and "incomplete executions"?

**Comment by aherrmann** [comment]
I see, thanks for explaining this distinction. Naively, I would have expected illegal use of `dontCheck` to cause test failure (independent of predicate), since I viewed it as part of the test infrastructure. Maybe an addition to the `dontCheck` haddocks like the following could help to clarify that?

> This must be the first thing done in the main thread. Violating this condition will result in the computation failing with IllegalDontCheck. *The test-case can still succeed if the used predicate allows for a failing computation.*

Out of curiosity, is there an anticipated use-case where `dontCheck` would not be the first instruction and success of a test-case with a predicate like `alwaysSame` would be expected by the user?

**Comment by barrucadu** [comment]
I'll add something like that to the Haddocks, thanks.

> Out of curiosity, is there an anticipated use-case where `dontCheck` would not be the first instruction and success of a test-case with a predicate like `alwaysSame` would be expected by the user?

Not really, no.
