### ISSUE TITLE
the @mkWeakTVar@ functions are -- not provided.

### ISSUE THREAD

**Issue by tonyday567** [barrucadu/dejafu#249]
I was wondering why the weak pointers are not provided - technical difficulties?

Context is I'm looking to port pipes-concurrency (at least conceptually) which makes use of this functionality eg https://github.com/Gabriel439/Haskell-Pipes-Concurrency-Library/blob/master/src/Pipes/Concurrent.hs#L212

**Comment by barrucadu** [comment]
Yes, weak pointers are difficult.  The problem is that adding them introduces another source of nondeterminism: which is, when the garbage collector gets scheduled relative to everything else.  Modelling this in a way which isn't hopelessly incomplete is tricky.

Having said that, `mkWeakTVar` is a concurrency operation, so it's definitely in scope.  It just needs some careful thought.

---

Here's an immediate thought for how this could possibly work:

1. Have a `TVar` containing a list of actions to run.
2. Add another  field to https://github.com/barrucadu/dejafu/blob/d90246930025d7342b4d1b0d6893c5a4220c2f41/dejafu/Test/DejaFu/Conc/Internal/STM.hs#L108

    which holds a weak `TVar` (a normal `TVar`, not a dejafu `TVar`).  This weak `TVar`, when garbage collected, adds its action to the list mentioned in (1).
3. Introduce a "garbage collector thread" which, when scheduled, picks an item from the list and runs it.

(this is confusing! maybe I should call `dejafu`'s internal model of things a "`ModelCRef`", "`ModelMVar`", and "`ModelTVar`" so it's clear what level I'm talking about)

I think all the internal state would need to be super-strict to avoid holding on to indirect references to these weak `TVar`s.  We'd also probably want to call `performGC` or `performMinorGC`: that's expensive, but we only need to do it while we have live weak `TVar`s

It would probably still only be an approximation, but it would be reasonably good.

---

I'm pretty busy for the next few months (finishing my Ph.D this month, moving cities and starting a job next month, going to a conference the month after), so I can't promise any sort of timely work on this, but I'll keep it in mind.

However, if you're super-motivated, I could definitely help guide an implementation of this (don't worry, I'm not expecting a positive answer here).

**Comment by tonyday567** [comment]
Thanks for the considered reply.

I don't actually like the usage in pipes-concurrency; that we should find a way to definitively (deterministically) close something off once it finalises rather than rely on the GC.  So I was half hoping for a 'it can't be done' to confirm my bias.

I'm way too new to the library to productively hack in as you suggest.  But am enjoying it as a user - it's been a good exercise so far to polymorph my code to MonadConc and tighten up the api.
