### ISSUE TITLE
DejaFu seems to incorrectly model this program

### ISSUE THREAD

**Issue by mitchellwrosen** [barrucadu/dejafu#324]
Hi, thanks again for the awesome library :)

I think I've encountered a case where dejafu does not behave like GHC (but I'm not positive). Here's a [repo](https://github.com/mitchellwrosen/dejafu-bug) that can be run with `cabal run`; here's the source:

```haskell
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Main where

import Control.Concurrent.Classy
import Control.Exception (Exception, SomeException)
import Test.DejaFu

main :: IO Bool
main =
  autocheck do
    var :: MVar (Program Basic IO) (Either SomeException ()) <- newEmptyMVar

    threadId <-
      uninterruptibleMask \restore ->
        fork do
          result <- try (restore (throw A))
          putMVar var result

    killThread threadId

    _ <- takeMVar var

    pure ()

try :: (Exception e, MonadConc m) => m a -> m (Either e a)
try action =
  catch (Right <$> action) (pure . Left)

data A = A
  deriving stock (Show)
  deriving anyclass (Exception)
```

And the output:

```
[fail] Successful
    [deadlock] S0-----S1---P0--
[fail] Deterministic
    [deadlock] S0-----S1---P0--

    () S0-----S1-------S0----
```

### What's going on

- A thread is forked in a `MaskedUninterruptible` masking state. **This thread should always put to an MVar**, per its installing an exception handler before restoring the masking state:

    ```haskell
    result <- try (restore ...)
    putMVar var result
    ```

- Meanwhile, the main thread throws this thread a `ThreadKilled`, then takes from the MVar.

- The main thread succeeds in taking the thread down, so it **doesn't put to the MVar** (later observed by a deadlock).

I spent some time making a prettier output of the thread actions. First, `main` spawns the thread, then blocks on throwing it an exception because it hasn't been scheduled yet.

```
[main]
  ...
  BlockedThrowTo thread#1
```

Then, thread#1 is scheduled; here's its entire trace:

```
[thread#1]
  Catching
  SetMaskingState Unmasked
  Throw False -- my 'throw A', False because it didn't take me down
```

Then, main is scheduled again, which succeeds in taking down thread#1.

```
[main]
  ThrowTo thread#1 True
  ...
```

### Why I think it's a bug

I don't think main's `ThrowTo` should have taken down thread#1 here, because it had installed an exception handler. I haven't dug around the internals of dejafu, but it seems like the handler gets "used up" by the thread's _own_ call to `throw A`.

**Comment by barrucadu** [comment]
Exception handling has caused so many difficulties 😞 

```haskell
      uninterruptibleMask \restore ->
        fork do
          result <- try (restore (throw A))
```

I see, because the exception handler is installed *outside* the `restore`, when the handler is called (either by `throw` or `throwTo`), the masking state should be set back to uninterruptible.  Therefore, it's incorrect for `throw` to jump to the handler *without* restoring the masking state.

Does that seem a correct explanation of the problem to you?

---

The implementation of `throwTo` looks ok, it starts by looking up the thread and checking if it's interruptible: https://github.com/barrucadu/dejafu/blob/57d3c45350c739912fb7c6abca5337ecb89310fb/dejafu/Test/DejaFu/Conc/Internal.hs#L547-L552

I think part of the problem is in how `ACatching`, the action which installs an exception handler, works: https://github.com/barrucadu/dejafu/blob/57d3c45350c739912fb7c6abca5337ecb89310fb/dejafu/Test/DejaFu/Conc/Internal/Threading.hs#L92-L97

The code is a bit of a mess, but the key detail is that, rather than atomically restoring the masking state when the jump out of the `restore`d context happens, it's done as the first step of the exception handler.

Therefore there is a race condition (which dejafu finds): `throw` pops the exception handler from the stack, the main thread starts executing again, and uses `throwTo` to kill the target thread.

The desired masking state should probably be recorded as data inside the `Handler` value, and restored when the handler is jumped to.

---

I could write up some thoughts on how to fix it if you'd like to give it a go, but if not I should be able to get to it some time this weekend.
