### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/dejafu#5]
Currently the only not-immediately-trivial example is the logger, it would be nice to have more (and maybe rename "tests" to "examples", and drop the trivial ones).

**Comment by barrucadu** [comment]
I have some things on my office machine. Need to tidy those up and then include them into the test suite.

**Comment by jxv** [comment]
There's been a lot of new and useful features since 0.2.0.0, which I wish were on hackage and stackage.  I hope the lack of documentation isn't blocking the release. Unless there's some larger architectural breakages or other plans brewing, I would request to upload more frequently with the small changes.
