### ISSUE TITLE
STM retry produces erroneous deadlock 

### ISSUE THREAD

**Issue by bosu** [barrucadu/dejafu#55]
The following correct program:

> module T where
>
> import Control.Concurrent.Classy
> import Test.DejaFu
> import Test.DejaFu.Deterministic
>
> doit :: MonadConc m => m Bool
> doit = do
>     a <- atomically $ newTQueue
>     b <- atomically $ newTQueue
>     fork $ atomically $ writeTQueue b True
>     atomically $ both a b
>     where both a b = readTQueue a \`orElse\` readTQueue b \`orElse\` retry
>
> main :: IO ()
> main = autocheck doit >>= print

Produces the following error:

> *T> main
> [fail] Never Deadlocks (checked: 1)
>	[stm-deadlock] S0----S1--
>	  0: main
> [pass] No Exceptions (checked: 1)
> [pass] Consistent Result (checked: 1)
> False

**Comment by barrucadu** [comment]
Thanks for reporting this.

It looks like it's due to [how I have implemented `orElse`](https://github.com/barrucadu/dejafu/blob/master/dejafu/Test/DejaFu/STM/Internal.hs#L160): in the retry case, it *throws away* the `TVar`s the left read from; whereas they should be added to the list that the transaction as a whole read from. Looks like my past code golfing got the better of me.

**Comment by bosu** [comment]
Thanks for the prompt fix!
